### ISSUE TITLE
FaHCore failed

### ISSUE THREAD

**Issue by Blackraz0r** [linuxserver/docker-foldingathome#5] opened 2020-05-05 22:20 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
container should start and begnn folding

## Current Behavior
it starts ent trows an error when starting to fold:

## Steps to Reproduce
1. Start docker
2. setup identity
3. begin folding
4. crash

## Environment
openmediavault 5.4.5.3 / debian kernel 5.5
**CPU architecture:** i3 6100
**How docker service was installed:**     via openmediavault 

## Command used to create docker container (run/create/compose/screenshot)
i used portainer and did this:
```
docker run -d\
  --name=foldingathome \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 7396:7396 \
  -p 36330:36330 `#optional` \
  -v /path/to/data:/config \
  --restart unless-stopped \
  linuxserver/foldingathome
```

## Docker logs
https://pastebin.com/HPcLx0dC

**Comment by tobbenb** [comment] 2020-05-06 08:02
This is a support issue and not a bug. GitHub is only for bugs. Jump on discord or our discourse forum for support.

Closing this as you haven't specified the correct host path for /config mount.

**Closed** 2020-05-06 08:02 UTC

**Comment by Blackraz0r** [comment] 2020-05-06 13:38
as you wish. here is the hostpath for /config:

/export/VM/Docker/Volumes/FaH/config

can you pls reopen it now ? as it istn working out of the box with no configuration at all there is a bug obviously? ;)

**Comment by aptalca** [comment] 2020-05-06 14:42
It passes our numerous tests with basic functionality and has more than half a million pulls. I'd say obviously pebcak

Also see here for the latest build result where you can clearly see it is working: https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/foldingathome/7.6.13-ls3/index.html
